package ampc.com.gistone.util;

import java.util.ArrayList;
import java.util.List;

public class ColorUtil {
	private String colorCode;
	private String colorName;
	public String getColorCode() {
		return colorCode;
	}
	public void setColorCode(String colorCode) {
		this.colorCode = colorCode;
	}
	public String getColorName() {
		return colorName;
	}
	public void setColorName(String colorName) {
		this.colorName = colorName;
	}
	
	public ColorUtil(String colorCode,String colorName){
		this.colorCode=colorCode;
		this.colorName=colorName;
	}
	/**
	 * 定义默认颜色帮助类
	 */
	public static List<ColorUtil> getColor(){
		List<ColorUtil> list=new ArrayList<ColorUtil>();
		ColorUtil color=null;
		color=new ColorUtil("f0f8ff","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("00ced1","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("556b2f","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("8fbc8f","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("8b0000","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("bdb76b","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("483d8b","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("a9a9a9","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("696969","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("b8860b","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("ff8c00","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("00008b","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("6400","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("008b8b","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("e9967a","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("dc143c","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("2f4f4f","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("8b008b","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("9400d3","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("9932cc","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("ffebcd","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("f5fffa","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("7fffd4","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("afeeee","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("98fb98","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("eee8aa","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("db7093","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("7cfc00","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("d2b48c","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("32cd32","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("ffa500","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("00ff7f","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("dcdcdc","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("fff0f5","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("e6e6fa","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("da70d6","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("4b0082","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("ffefd5","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("ffc0cb","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("b0e0e6","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("808000","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("4682b4","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("faebd7","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("fff5ee","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("80","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("2e8b57","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("bc8f8f","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("a52a2a","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("ff4500","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("ff0000","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("ff00ff","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("fffaf0","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("4169e1","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("f0e68c","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("7fff00","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("adff2f","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("9acd32","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("ffff00","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("808080","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("708090","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("b22222","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("d8bfd8","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("daa520","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("ffd700","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("ffe4c4","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("6495ed","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("5f9ea0","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("0000ff","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("fdf5e6","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("ffb6c1","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("b0c4de","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("20b2aa","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("d3d3d3","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("778899","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("add8e6","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("90ee90","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("e0ffff","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("ffa07a","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("f08080","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("87cefa","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("ffe4b5","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("8000","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("fff8dc","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("f5f5dc","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("cd853f","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("f0fff0","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("ffdead","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("fffacd","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("f5deb3","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("00ffff","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("ffe4e1","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("d2691e","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("40e0d0","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("00ffff","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("ff69b4","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("228b22","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("f4a460","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("ff7f50","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("1e90ff","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("ff1493","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("6b8e23","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("00bfff","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("6a5acd","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("deb887","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("8080","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("800000","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("00ff00","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("ffdab9","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("f0ffff","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("87ceeb","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("ff6347","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("fa8072","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("fffafa","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("faf0e6","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("f5f5f5","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("dda0dd","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("c0c0c0","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("cd5c5c","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("f8f8ff","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("a0522d","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("7b68ee","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("00fa9a","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("ba55d3","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("3cb371","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("191970","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("0000cd","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("48d1cc","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("66cdaa","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("c71585","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("9370db","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("8b4513","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("ff00ff","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("ee82ee","btn-cuoshi-qian");
		list.add(color);
		color=new ColorUtil("8a2be2","btn-cuoshi-shen");
		list.add(color);
		color=new ColorUtil("800080","btn-cuoshi-shen");
		list.add(color);
		return list;
	}
}
